export const RESTAURANT_TYPES = [
  'Fine Dining',
  'Casual Dining',
  'Fast Casual',
  'Quick Service',
  'Coffee Shop',
  'Bakery',
  'Pizzeria',
  'Steakhouse',
  'Seafood',
  'Italian',
  'Mexican',
  'Asian',
  'Indian',
  'Thai',
  'Chinese',
  'Japanese',
  'Mediterranean',
  'American',
  'French',
  'German',
  'Spanish',
  'Bar & Grill',
  'Sports Bar',
  'Wine Bar',
  'Brewery',
  'Buffet',
  'Food Truck',
  'Deli',
  'Bistro',
  'Cafe',
  'Other'
];

export const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

export const BUSINESS_TYPES = [
  'Sole Proprietorship',
  'Partnership',
  'LLC',
  'Corporation',
  'Franchise',
  'Other'
];

export const SEATING_CAPACITY_RANGES = [
  { value: '1-25', label: '1-25 seats' },
  { value: '26-50', label: '26-50 seats' },
  { value: '51-100', label: '51-100 seats' },
  { value: '101-200', label: '101-200 seats' },
  { value: '201-500', label: '201-500 seats' },
  { value: '500+', label: '500+ seats' }
];

export const PRICE_RANGES = [
  { value: '$', label: '$ - Budget friendly' },
  { value: '$$', label: '$$ - Moderate' },
  { value: '$$$', label: '$$$ - Upscale' },
  { value: '$$$$', label: '$$$$ - Fine dining' }
];

export const DEFAULT_HOURS = {
  'Monday': '9:00 AM - 10:00 PM',
  'Tuesday': '9:00 AM - 10:00 PM',
  'Wednesday': '9:00 AM - 10:00 PM',
  'Thursday': '9:00 AM - 10:00 PM',
  'Friday': '9:00 AM - 11:00 PM',
  'Saturday': '9:00 AM - 11:00 PM',
  'Sunday': '9:00 AM - 9:00 PM'
};